spring:
  application:
    name: Concurrent
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/concurrent-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true