spring:
  application:
    name: DB_Search
  #MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/db-search-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  #Cache
  cache:
    type: redis
    cache-names:
      - redis-users
      - caffeine-users

  #Async
  task:
    execution:
      pool:
        max-size: 10
        core-size: 5

  #Redis
  data:
    redis:
      host: db-search-redis
      port: 6379