spring:
  application:
    name: DB_Search
  #MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/db-search-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  #Redis
  data:
    redis:
      host: localhost
      port: 6379

  #Cache
  cache:
    type: redis
    cache-names:
      - redis-users
      - caffeine-users

  #Async
  task:
    execution:
      pool:
        max-size: 10
        core-size: 5

springdoc:
  swagger-ui:
    tags-sorter: alpha